In [1]:
#importing required library
import pandas as pd
import numpy as np

In [2]:
#reading train and test data 
training_data= pd.read_excel(r'C:\Users\harita\Mypython\Machine learning\KNN\Early diabetes_train.xlsx',header=0)
testing_data= pd.read_excel(r'C:\Users\harita\Mypython\Machine learning\KNN\Early diabetes_test.xlsx',header=0)



(500, 17)
(20, 17)


In [3]:
#loading train data head to check it been imported properly
training_data.head()

Age Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0  40.0   Male       No        Yes                 No      Yes         No   
1  58.0   Male       No         No                 No      Yes         No   
2  41.0   Male      Yes         No                 No      Yes        Yes   
3   NaN   Male       No         No                Yes      Yes        Yes   
4  60.0   Male      Yes        Yes                Yes      Yes        Yes   

  Genital thrush visual blurring Itching Irritability delayed healing  \
0             No              No     Yes           No             Yes   
1             No             Yes      No           No              No   
2             No              No     Yes           No             Yes   
3            Yes              No     Yes           No             Yes   
4             No             Yes     Yes          Yes             Yes   

  partial paresis muscle stiffness Alopecia Obesity     class  
0              No              Yes      Yes     Yes  Positive  
1             Yes               No      Yes      No  Positive  
2              No              Yes      Yes      No  Positive  
3              No               No       No      No  Positive  
4             Yes              Yes      Yes     Yes  Positive

In [5]:
#loading test data head to check it been imported properly
testing_data.head()

Age  Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0  60.0    Male       No         No                NaN       No         No   
1  58.0    Male       No         No                 No      Yes         No   
2  39.0  Female      Yes        Yes                Yes       No        Yes   
3  54.0    Male       No         No                 No       No         No   
4  67.0    Male       No         No                 No      Yes         No   

  Genital thrush visual blurring Itching Irritability delayed healing  \
0             No              No      No           No              No   
1             No              No     Yes           No             Yes   
2             No              No     Yes           No             Yes   
3             No              No      No           No              No   
4             No              No     Yes           No             Yes   

  partial paresis muscle stiffness Alopecia Obesity     class  
0              No               No       No     Yes  Negative  
1              No              Yes      Yes      No  Negative  
2             Yes               No       No      No  Positive  
3              No               No       No      No  Negative  
4              No               No      Yes      No  Negative

In [9]:
#checking shape and basic info of the data
print(training_data.shape)
print(testing_data.shape)

print(training_data.info())
print(testing_data.info())

(500, 17)
(20, 17)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Age                 478 non-null    float64
 1   Gender              500 non-null    object 
 2   Polyuria            500 non-null    object 
 3   Polydipsia          500 non-null    object 
 4   sudden weight loss  491 non-null    object 
 5   weakness            500 non-null    object 
 6   Polyphagia          500 non-null    object 
 7   Genital thrush      500 non-null    object 
 8   visual blurring     500 non-null    object 
 9   Itching             500 non-null    object 
 10  Irritability        500 non-null    object 
 11  delayed healing     500 non-null    object 
 12  partial paresis     500 non-null    object 
 13  muscle stiffness    491 non-null    object 
 14  Alopecia            500 non-null    object 
 15  Obesity             500 non-null    ob

In [63]:
#Checking wheather the train and test data has Missing Values

print(training_data.isnull().sum())
print(testing_data.isnull().sum())

Age                   22
Gender                 0
Polyuria               0
Polydipsia             0
sudden weight loss     9
weakness               0
Polyphagia             0
Genital thrush         0
visual blurring        0
Itching                0
Irritability           0
delayed healing        0
partial paresis        0
muscle stiffness       9
Alopecia               0
Obesity                0
class                  0
dtype: int64
Age                   2
Gender                0
Polyuria              0
Polydipsia            0
sudden weight loss    3
weakness              0
Polyphagia            0
Genital thrush        0
visual blurring       0
Itching               0
Irritability          0
delayed healing       0
partial paresis       0
muscle stiffness      2
Alopecia              0
Obesity               0
class                 0
dtype: int64


In [10]:
#"Age", "sudden weight loss" and "muscle stiffness" has missg values in both train and test data. 
# Replacing "sudden weight loss"and "muscle stiffness" variables with mode value because they are categorical.
# Replacing "Age" variable with mean value because they are numeric

training_data["Age"].fillna(int(training_data["Age"].mean()),inplace=True)
training_data["sudden weight loss"].fillna(training_data["sudden weight loss"].mode()[0],inplace=True)
training_data["muscle stiffness"].fillna(training_data["muscle stiffness"].mode()[0],inplace=True)
                                         
testing_data["Age"].fillna(int(testing_data["Age"].mean()),inplace=True)
testing_data["sudden weight loss"].fillna(testing_data["sudden weight loss"].mode()[0],inplace=True)
testing_data["muscle stiffness"].fillna(testing_data["muscle stiffness"].mode()[0],inplace=True)

print(training_data.isnull().sum())
print(testing_data.isnull().sum())

Age                   0
Gender                0
Polyuria              0
Polydipsia            0
sudden weight loss    0
weakness              0
Polyphagia            0
Genital thrush        0
visual blurring       0
Itching               0
Irritability          0
delayed healing       0
partial paresis       0
muscle stiffness      0
Alopecia              0
Obesity               0
class                 0
dtype: int64
Age                   0
Gender                0
Polyuria              0
Polydipsia            0
sudden weight loss    0
weakness              0
Polyphagia            0
Genital thrush        0
visual blurring       0
Itching               0
Irritability          0
delayed healing       0
partial paresis       0
muscle stiffness      0
Alopecia              0
Obesity               0
class                 0
dtype: int64


In [ ]:
#We are no checking for the Outliers because KNN doesnot affected by outlier. never going to affect our model

In [11]:
#Converting categorical variable into numerical using lable encoder

colname=[]
for x in training_data.columns:
    if training_data[x].dtype=='object':
        colname.append(x)
colname

['Gender',
 'Polyuria',
 'Polydipsia',
 'sudden weight loss',
 'weakness',
 'Polyphagia',
 'Genital thrush',
 'visual blurring',
 'Itching',
 'Irritability',
 'delayed healing',
 'partial paresis',
 'muscle stiffness',
 'Alopecia',
 'Obesity',
 'class']

In [12]:
from sklearn import preprocessing

le=preprocessing.LabelEncoder()

for x in colname:
    training_data[x]=le.fit_transform(training_data[x])
    testing_data[x]=le.fit_transform(testing_data[x])

In [13]:
#checking wheather above steps worked properly
training_data.head()

Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0  40.0       1         0           1                   0         1   
1  58.0       1         0           0                   0         1   
2  41.0       1         1           0                   0         1   
3  48.0       1         0           0                   1         1   
4  60.0       1         1           1                   1         1   

   Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
0           0               0                0        1             0   
1           0               0                1        0             0   
2           1               0                0        1             0   
3           1               1                0        1             0   
4           1               0                1        1             1   

   delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  \
0                1                0                 1         1        1   
1                0                1                 0         1        0   
2                1                0                 1         1        0   
3                1                0                 0         0        0   
4                1                1                 1         1        1   

   class  
0      1  
1      1  
2      1  
3      1  
4      1

In [14]:
testing_data.head()

Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0  60.0       1         0           0                   1         0   
1  58.0       1         0           0                   0         1   
2  39.0       0         1           1                   1         0   
3  54.0       1         0           0                   0         0   
4  67.0       1         0           0                   0         1   

   Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
0           0               0                0        0             0   
1           0               0                0        1             0   
2           1               0                0        1             0   
3           0               0                0        0             0   
4           0               0                0        1             0   

   delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  \
0                0                0                 0         0        1   
1                1                0                 1         1        0   
2                1                1                 0         0        0   
3                0                0                 0         0        0   
4                1                0                 0         1        0   

   class  
0      0  
1      0  
2      1  
3      0  
4      0

In [16]:
#creating X and Y variables

X_train = training_data.values[:,0:-1]
X_test = testing_data.values[:,0:-1]

Y_train = training_data.values[:,-1]
Y_test = testing_data.values[:,-1]

Y_train= Y_train.astype(int)
Y_test= Y_test.astype(int)

In [17]:
print(X_train)
print(Y_train)

[[40.  1.  0. ...  1.  1.  1.]
 [58.  1.  0. ...  0.  1.  0.]
 [41.  1.  1. ...  1.  1.  0.]
 ...
 [38.  1.  0. ...  0.  0.  0.]
 [35.  1.  0. ...  0.  0.  0.]
 [61.  1.  0. ...  0.  1.  0.]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1
 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1
 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0
 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [22]:
#scaling is necessary to get data in one range

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X_train)
# while working on seperate train and test data fit scaler object only upon the train data
#scaler object will learn for train data
#and use the same scaler object to transfer both train as well as test data


X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)


## KNN

In [19]:
#now we are all set to run the model
# Running KNN (sqrt approach) model 

import numpy as np

from sklearn.neighbors import KNeighborsClassifier

model_KNN= KNeighborsClassifier(n_neighbors= int(np.sqrt(len(X_train))),
                                    metric= 'euclidean')

#fit the model on the data and predict the values

model_KNN.fit(X_train,Y_train)

Y_pred= model_KNN.predict(X_test)

print(list(zip(Y_test,Y_pred)))

[(0, 0), (0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (1, 1), (0, 0), (1, 1), (0, 0), (1, 1), (0, 0), (1, 1), (1, 1), (0, 0), (1, 1)]


In [21]:
#Model Evaluation

from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[10  0]
 [ 0 10]]

Classification report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

Accuracy of the model:  1.0


In [23]:
# trial n error

from sklearn.metrics import accuracy_score
my_dict={}
for K in range(1,15):
    model_KNN = KNeighborsClassifier(n_neighbors=K,metric="euclidean")
    model_KNN.fit(X_train, Y_train) 
    Y_pred = model_KNN.predict(X_test)
    print ("Accuracy is ", accuracy_score(Y_test,Y_pred), "for K-Value:",K)
    my_dict[K]=accuracy_score(Y_test,Y_pred)

Accuracy is  1.0 for K-Value: 1
Accuracy is  1.0 for K-Value: 2
Accuracy is  1.0 for K-Value: 3
Accuracy is  1.0 for K-Value: 4
Accuracy is  1.0 for K-Value: 5
Accuracy is  1.0 for K-Value: 6
Accuracy is  1.0 for K-Value: 7
Accuracy is  1.0 for K-Value: 8
Accuracy is  1.0 for K-Value: 9
Accuracy is  1.0 for K-Value: 10
Accuracy is  1.0 for K-Value: 11
Accuracy is  1.0 for K-Value: 12
Accuracy is  1.0 for K-Value: 13
Accuracy is  1.0 for K-Value: 14


## Logistic regression

In [25]:
#Trying out logistic regression
from sklearn.linear_model import LogisticRegression
#create a model
classifier=LogisticRegression()
#fitting training data to the model
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(0, 0), (0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (1, 1), (0, 0), (1, 1), (0, 0), (1, 1), (0, 0), (1, 1), (1, 1), (0, 0), (1, 1)]


In [26]:
#model Evaluation
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

confusion_matrix=confusion_matrix(Y_test,Y_pred)
print(confusion_matrix)
print()
print("Classification report: ")

print(classification_report(Y_test,Y_pred))

accuracy_score=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",accuracy_score)

[[10  0]
 [ 0 10]]

Classification report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

Accuracy of the model:  1.0
